services:
  - type: web
    name: evaluation-platform-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: evaluation_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ALLOWED_ORIGINS
        value: https://votre-app-frontend.vercel.app,https://votre-app-admin.vercel.app
      - key: UPLOAD_DIR
        value: /app/uploads
      - key: OLLAMA_API_URL
        value: https://votre-ollama-service.onrender.com

databases:
  - name: evaluation_db
    databaseName: evaluation_db
    user: evaluation_user 